30
-SSSSSSS-SSSSSSSS-
-S-S-S-S-S-S-S-S-S-
-S--S--S--S--S--S--S--S--S-
-S---B-S---B-S---B-S--B-S---B-S---B-S---B-S---BS-
--BSD--BSD--BSD--BSD-S---BDS--S--D--BSD--BDS-
-B-S-D--B-S-D--B-S-D--B-S-D-B--S-D-B--S-D--B-S-D-
--S--B--S--B--D--B--S--B--
DBS--S--B--D--B--S--BDS
-DBS--DBS--D-DBS--S--BDS-
-BBS--BDS--D-BBS--BS--BSS-
-S--SBS--BDS--BDD--SSB--BBS--DBD--SDD--DBB--SDS--
-B-DS--DB--SD--BD--SB--SS--DD--BB--S-
DSS-B-S-D---BSSD-DBSS--SSBD--DBSBDS--S-D-B-
D
-S-
--B-
--B-S-
D--B-S-D
S--D-B-S
D-----
--------D
S-----
--------S
B-----
--------B
S-----B
S-DDD---BD--B
BBBB-----SSSS
SSSS-----BBBB
SSSS--DDDD---BBBB
